# Generated by Django 4.2.19 on 2025-04-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                db_index=True, default="+12345678901", max_length=70, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("STAFF", "Staff"),
                    ("DISPATCHER", "Dispatcher"),
                    ("PATIENT", "Patient"),
                ],
                default="PATIENT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
    ]
